stages:
    - deploy
    
pages:
    stage: deploy
    script:
        - mkdir public
        - cp -r src/main/webapp/* public
    artifacts:
        paths:
            - public
    only:
        - master

