stages:
    - deploy
    
pages:
    stage: deploy
    script:
        - mkdir .public
        - cp -r src/main/webapp/* .public
        - mv .public public
    artifacts:
        paths:
            - public
    only:
        - master

